<a href="https://colab.research.google.com/github/aakashkumar089/Class-notes/blob/main/OTS_Gradient_Boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## It is for medium level Dataset
## Less complexity than XG Boost

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
df = pd.read_csv("/content/mushrooms.csv")

In [ ]:
df.head()

  class cap-shape cap-surface  ... spore-print-color population habitat
0     p         x           s  ...                 k          s       u
1     e         x           s  ...                 n          n       g
2     e         b           s  ...                 n          n       m
3     p         x           y  ...                 k          s       u
4     e         x           s  ...                 n          a       g

[5 rows x 23 columns]

In [ ]:
## Data Preperation
X = df.drop('class',axis = 1)

y = df['class']

In [ ]:
X = pd.get_dummies(X,drop_first=True,dtype=int)

X

      cap-shape_c  cap-shape_f  cap-shape_k  ...  habitat_p  habitat_u  habitat_w
0               0            0            0  ...          0          1          0
1               0            0            0  ...          0          0          0
2               0            0            0  ...          0          0          0
3               0            0            0  ...          0          1          0
4               0            0            0  ...          0          0          0
...           ...          ...          ...  ...        ...        ...        ...
8119            0            0            1  ...          0          0          0
8120            0            0            0  ...          0          0          0
8121            0            1            0  ...          0          0          0
8122            0            0            1  ...          0          0          0
8123            0            0            0  ...          0          0          0

[8124 rows x 95 columns]

In [ ]:
y.head()

0    p
1    e
2    e
3    p
4    e
Name: class, dtype: object

In [ ]:
y.unique()

array(['p', 'e'], dtype=object)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=101)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = {"n_estimators":[1,5,10,20,40,100],'max_depth':[3,4,5,6]}

In [ ]:
gb_model = GradientBoostingClassifier()

In [ ]:
grid = GridSearchCV(gb_model,param_grid)

## Train the model

In [ ]:
grid.fit(X_train,y_train)

GridSearchCV(estimator=GradientBoostingClassifier(),
             param_grid={'max_depth': [3, 4, 5, 6],
                         'n_estimators': [1, 5, 10, 20, 40, 100]})

In [ ]:
grid.best_params_

{'max_depth': 4, 'n_estimators': 100}

In [ ]:
grid.best_estimator_

GradientBoostingClassifier(max_depth=4)

## Performance

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score